name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "include/**"
      - "src/**"
      - "docs/**"
      - "README.md"
      - ".github/workflows/documentation.yml"

  pull_request:

  workflow_dispatch:

jobs:
  documentation:
    name: Build Documentation

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install documentation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Create documentation directory
        run: mkdir -p build/docs

      - name: Generate documentation
        run: doxygen docs/Doxyfile

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: nane-documentation
          path: build/docs/html

  pages:
    name: Prepare GitHub Pages

    if: github.event.repository.private == false

    needs:
      - documentation

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download documentation
        uses: actions/download-artifact@v5
        with:
          name: nane-documentation
          path: build/docs/html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Disable Jekyll
        run: touch build/docs/html/.nojekyll

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/docs/html

  deploy:
    name: Deploy GitHub Pages

    if: github.event.repository.private == false

    needs:
      - pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
